name: CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    # run CI every day even if no PRs/merges occur
    - cron:  '0 12 * * *'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: deps
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format

      - name: lint
        run: |
          mkdir build && cd build
          cmake ..
          cmake --build . --target format
          cd .. && git diff --exit-code
  build:
    strategy:
      matrix:
        platform: ["ubuntu-latest"]
        build-type: ["Debug", "Release"]
        compiler:
        - { CC: "clang", CXX: "clang++" }
        - { CC: "gcc", CXX: "g++" }
        exclude:
        - platform: macos-latest
          compiler: { CC: "gcc", CXX: "g++" }
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2

    - name: deps
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen libssl-dev

    - name: configure
      run: |
        mkdir build && cd build
        cmake \
          -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} \
          -DBUILD_DOCUMENTATION=1 \
          -DBUILD_SVCLI=1 \
          ..

    - name: build
      working-directory: build
      env:
        CC: ${{ matrix.compiler.CC }}
        CXX: ${{ matrix.compiler.CXX }}
      run: cmake --build .

    - name: docs
      working-directory: build
      run: cmake --build . --target doc
