name: CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    # run CI every day even if no PRs/merges occur
    - cron:  '0 12 * * *'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: deps
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format-9

      - name: lint
        run: |
          mkdir build && cd build
          cmake ..
          cmake --build . --target smolverify_format
          cd .. && git diff --exit-code

  build-linux:
    strategy:
      matrix:
        build-type: ["Debug", "Release"]
        build-shared: ["0", "1"]
        compiler:
        - { CC: "clang", CXX: "clang++" }
        - { CC: "gcc", CXX: "g++" }
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: deps
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz libssl-dev

    - name: configure
      run: |
        mkdir build && cd build
        cmake \
          -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} \
          -DBUILD_SHARED_LIBS=${{ matrix.build-shared }} \
          -DBUILD_DOCUMENTATION=1 \
          -DBUILD_SVCLI=1 \
          -DBUILD_TESTS=1 \
          ..

    - name: build
      working-directory: build
      env:
        CC: ${{ matrix.compiler.CC }}
        CXX: ${{ matrix.compiler.CXX }}
      run: cmake --build .

    - name: tests
      working-directory: build
      run: ./test/smolverify_test

    - name: docs
      working-directory: build
      run: cmake --build . --target doc

  build-macos:
    strategy:
      matrix:
        build-type: ["Debug", "Release"]
        build-shared: ["0", "1"]
        compiler:
        - { CC: "clang", CXX: "clang++" }
        - { CC: "gcc", CXX: "g++" }
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: deps
        run: |
          brew install icu4c openssl

      - name: configure
        run: |
          mkdir build && cd build
          cmake \
            -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl@1.1 \
            -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} \
            -DBUILD_SHARED_LIBS=${{ matrix.build-shared }} \
            -DBUILD_SVCLI=1 \
            -DBUILD_TESTS=1 \
            ..

      - name: build
        working-directory: build
        env:
          CC: ${{ matrix.compiler.CC }}
          CXX: ${{ matrix.compiler.CXX }}
        run: cmake --build .

      - name: tests
        working-directory: build
        run: ./test/smolverify_test

  build-windows:
    strategy:
      matrix:
        build-arch:
        - { arch: "x64", triplet: "x64-windows-static" }
        - { arch: "Win32", triplet: "x86-windows-static" }
        build-type: ["Debug", "Release"]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: deps
      run: |
        vcpkg install openssl --triplet ${{ matrix.build-arch.triplet }}

    - name: configure
      run: |
        mkdir build
        cd build
        cmake `
          -G "Visual Studio 16 2019" `
          -A ${{ matrix.build-arch.arch }} `
          -DOPENSSL_USE_STATIC_LIBS=1 `
          -DOPENSSL_ROOT_DIR=C:/vcpkg/installed/${{ matrix.build-arch.triplet }} `
          -DBUILD_SVCLI=1 `
          -DBUILD_TESTS=1 `
          ..

    - name: build
      working-directory: build
      run: cmake --build . --config ${{ matrix.build-type }}

    - name: Upload build
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.build-arch.arch}}-${{ matrix.build-type }}-smolverify
        path: build

    - name: tests
      working-directory: build
      run: |
        Test-Path ./test/${{ matrix.build-type }}/smolverify_test.exe
        ./test/${{ matrix.build-type }}/smolverify_test.exe
