name: docs-deploy

on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: deps
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen libssl-dev

      - name: configure
        run: |
          mkdir build && cd build
          cmake \
            -DBUILD_DOCUMENTATION=1 \
            ..
      - name: docs
        working-directory: build
        run: cmake --build . --target doc

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3.5.6
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/doc/html
          publish_branch: gh-pages
          force_orphan: true
